Fix build due to child package .json file
error TS2732: Cannot find module 'core-js/package.json'. Consider using '--resolveJsonModule'
to import module with '.json' extension.

Task [#2]