Include svelte rules form eslint-config
Must override types in ts-config because bundler resolution is required to
resolve `FlatConfig`

 error TS2307: Cannot find module '@typescript-eslint/utils/ts-eslint' or its corresponding type declarations.

Task [#5]